# Generated by Django 4.0.1 on 2022-01-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEns', models.CharField(max_length=20)),
                ('PrenomEns', models.CharField(max_length=20)),
                ('Ntele', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('NomEntreprise', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe_Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Etudians', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPr', models.CharField(max_length=20)),
                ('PrenomPr', models.CharField(max_length=20)),
                ('Ntelephone', models.IntegerField(null=True)),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Stage',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Duree', models.IntegerField()),
                ('PeriodeDebut', models.DateField()),
                ('PeriodeFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('Convention_de_stage', models.FileField(null=True, upload_to='')),
                ('Rapport_de_stage', models.FileField(null=True, upload_to='')),
                ('Fiche_d_evaluation', models.FileField(null=True, upload_to='')),
                ('encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.enseignat')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.entreprise')),
                ('groupe_des_etudiants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.groupe_etudiant')),
                ('promoteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.promoteur')),
                ('type_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.type_stage')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEt', models.CharField(max_length=20)),
                ('PrenomEt', models.CharField(max_length=20)),
                ('Année_Etude', models.IntegerField(null=True)),
                ('Ntel', models.IntegerField(null=True)),
                ('groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.groupe_etudiant')),
            ],
        ),
    ]
