# Generated by Django 4.0.1 on 2022-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion', '0002_remove_etudiant_groupe_remove_promoteur_entreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEt', models.CharField(max_length=20)),
                ('PrenomEt', models.CharField(max_length=20)),
                ('Année_Etude', models.IntegerField(null=True)),
                ('Ntel', models.IntegerField(null=True)),
            ],
        ),
    ]
