# Generated by Django 4.0.1 on 2022-01-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_enseignat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enseignat',
        ),
    ]
