# Generated by Django 4.0.1 on 2022-01-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_enseignant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('NomEntreprise', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.groupe_etudiant'),
        ),
    ]
