# Generated by Django 4.0.1 on 2022-01-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_entreprise_etudiant_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPr', models.CharField(max_length=20)),
                ('PrenomPr', models.CharField(max_length=20)),
                ('Ntelephone', models.IntegerField(null=True)),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.entreprise')),
            ],
        ),
    ]
