# Generated by Django 4.0.1 on 2022-01-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_promoteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Stage',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Duree', models.IntegerField()),
                ('PeriodeDebut', models.DateField()),
                ('PeriodeFin', models.DateField()),
            ],
        ),
    ]
