# Generated by Django 4.0.1 on 2022-01-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0010_type_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('Convention_de_stage', models.FileField(null=True, upload_to='')),
                ('Rapport_de_stage', models.FileField(null=True, upload_to='')),
                ('Fiche_d_evaluation', models.FileField(null=True, upload_to='')),
                ('encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.enseignant')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.entreprise')),
                ('groupe_des_etudiants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.groupe_etudiant')),
                ('promoteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.promoteur')),
                ('type_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.type_stage')),
            ],
        ),
    ]
