# Generated by Django 4.0.1 on 2022-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0011_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='sujet',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
