# Generated by Django 4.0.1 on 2022-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0012_stage_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='Nombre_de_stageaires',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='PrenomEns',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
