# Generated by Django 4.0.1 on 2022-01-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0013_entreprise_nombre_de_stageaires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='Convention_de_stage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='Fiche_d_evaluation',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='Rapport_de_stage',
        ),
    ]
