# Generated by Django 4.0.1 on 2022-01-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0014_remove_stage_convention_de_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='Nombre_de_stageaires',
        ),
    ]
