# Generated by Django 4.0.1 on 2022-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0016_entreprise_nombre_de_stageaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe_etudiant',
            name='Nombre_Etudians',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
